name: test pipeline

on:
  push:
    branches:
      - master
      - dev

jobs:
  fs_scan_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy Security Scan (Dev)
        run: |
          trivy fs . -o dev_scan.json

  fs_scan_main:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run Trivy Security Scan (Main)
        run: |
          trivy fs . -o main_scan.json

  dev_docker_build:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image for Dev
        run: |
          cd /root/Backend-dev/bck_devops_testing
          docker build -t bckimage .

  main_docker_build:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image for Main
        run: |
          cd /root/Backend-dev/bck_devops_testing
          docker build -t bckimage .

  main_docker_dep:
    runs-on: self-hosted
    needs: main_docker_build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Run Docker container
        run: |
          docker run -d --name main_container bckimage
