name: test pipeline

on:
  push:
    branches:
      - master
      - dev

jobs:
  fs_scan_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy Security Scan (Dev)
        run: |
          trivy fs . -o dev_scan.json

  fs_scan_master:
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run Trivy Security Scan (Master)
        run: |
          trivy fs . -o master_scan.json

  dev_docker_build:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image for Dev
        run: |
          cd /root/Backend-dev/bck_devops_testing
          docker build -t bckimage:dev .

  master_docker_build:
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image for Master
        run: |
          cd /root/Backend-dev/bck_devops_testing
          docker build -t bckimage:latest .

  master_docker_deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    needs: master_docker_build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Run Docker container
        run: |
          docker run -d --name main_container bckimage:latest
