name: test pipeline 
on: 
 push: 
   branches:
    - master
    - dev 
jobs:
  fs_scan_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    steps:
      - name: checkout 
        uses: actions/checkout@v3 
      - name: fs scan dev
        run: |
           trivy fs . -o dev_scan.json 
           
  fs_scan_main:
     if: github.ref == 'refs/heads/main'
     runs-on: self-hosted
     steps:
       - name: checkout 
         uses: actions/checkout@v3 
       - name: fs scan main
         run: |
           trivy fs . -o dev_scan.json 
           
  dev_docker_build:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    steps:
      - name: checkout 
        uses: actions/checkout@v3
      - name: docker build dev 
        run: |
          docker-compose build . 
          
  main_docker_build:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: checkout 
        uses: actions/checkout@v3
      - name: docker build main
        run: |
          docker-compose build . 

          
  main_docker_dep:
    runs-on: self-hosted
    steps:
      - name: checkout 
        uses: actions/checkout@v3 
      - name: docker run main 
        run: | 
          docker-compose -p main up -d
