name: test pipeline

on:
  push:
    branches:
      - master # Change this to your branch name if it's different

jobs:
  fs_scan:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy Security Scan
        run: |
          trivy fs . -o scan.json

  docker_build:
    runs-on: self-hosted
    needs: fs_scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          cd /root/Backend-dev/bck_devops_testing
          docker build -t bckimage .

  docker_deploy:
    runs-on: self-hosted
    needs: docker_build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Run Docker container
        run: |
          docker run -d --name main_container bckimage
