name: Deploy and Run Docker container on EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your_dockerhub_username/bckimage:latest .
        docker push your_dockerhub_username/bckimage:latest

    - name: Deploy and Run Docker container on EC2
      env:
        HOST: 34.227.16.187
        USERNAME: veladandisoumith
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
        docker pull your_dockerhub_username/bckimage:latest
        docker stop myapp || true
        docker rm myapp || true
        docker run -d --name myapp -p 80:80 your_dockerhub_username/bckimage:latest
        EOF
      shell: bash
