name: CI/CD Pipeline for Dockerized App

on:
  push:
    branches:
      - master  # Trigger the pipeline on push to the master branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Using self-hosted runner

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub with your credentials
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: soumith362  # Docker Hub username
        password: 9705346780  # Docker Hub password

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t soumith362/bckimage:latest -f bck_devops_testing/Dockerfile bck_devops_testing/

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push soumith362/bckimage:latest

    # Step 6: Deploy Docker container on EC2 instance
    - name: Deploy Docker container on EC2
      env:
        HOST: 44.211.61.207  # Updated EC2 Public IP
        USERNAME: ubuntu  # EC2 SSH username
        PASSWORD: 9705346780  # EC2 password for SSH access
      run: |
        # Install sshpass if not installed
        sudo apt-get update && sudo apt-get install -y sshpass

        # SSH into EC2 and deploy the Docker container
        sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
        # Check if Docker is running on the EC2 instance
        docker info || exit 1  # This will fail the job if Docker isn't available

        # Pull the Docker image from Docker Hub
        docker pull soumith362/bckimage:latest || exit 1  # Fail if pull fails

        # Stop and remove any existing container (if running)
        docker stop my-app || true
        docker rm my-app || true

        # Run the new Docker container
        docker run -d --name my-app -p 80:80 soumith362/bckimage:latest || exit 1  # Fail if Docker run fails
        EOF
