name: Test Pipeline

on:
  push:
    branches:
      - master

jobs:
  docker-job:
    runs-on: hosting-self
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Run
        run: |
          docker run -d --name nginx -p 80:80 nginx
