name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if Dockerfile exists
      run: |
        if [ ! -f ./Dockerfile ]; then
          echo "Dockerfile does not exist in the repository root"
          exit 1
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t bckimage .

    # Optional: Add more steps here, like running tests, pushing the image to a registry, etc.
    # For example:
    # - name: Run tests
    #   run: docker run --rm bckimage <command-to-run-tests>
    #
    # - name: Log in to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #
    # - name: Push Docker image
    #   run: docker push bckimage
