name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  docker-job:
    runs-on: self-hosted  # Make sure your runner is correctly configured and online
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Dockerfile Presence
        run: |
          if [ ! -f ./Dockerfile ]; then
            echo "Dockerfile does not exist in the repository root"
            exit 1
          fi

      - name: Build Docker Image
        run: docker build -t backend-app .

      - name: Run Docker Container
        run: docker run -d --name backend-app -p 3000:3000 backend-app
