name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if Dockerfile exists
      run: |
        if [ ! -f ./Dockerfile ]; then
          echo "Dockerfile does not exist in the repository root"
          exit 1
        fi

    - name: Build Docker image
      run: docker build -t bckimage .
      # You can add more steps here, like running tests, pushing the image to a registry, etc.
